In [34]:
import numpy as np
from random import random, randint 

In [35]:
 #Замініть усі непарні числа в arr на -1 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
"""for i in arr:
    if i%2 !=0:
        arr[i]=-1"""
          
print(arr)
        

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
#Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr_1d= np.random.randint(1,11, size = (6,))
arr_2d = arr_1d.reshape(2,-1)
print(arr_1d, arr_2d)



[4 8 2 2 8 8] [[4 8 2]
 [2 8 8]]


In [37]:
#Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(1,10, size =(2,3))
c= np.vstack((a,b))
print(a,b, c)

[[1 3 4]
 [3 6 9]] [[2 1 8]
 [7 3 1]] [[1 3 4]
 [3 6 9]
 [2 1 8]
 [7 3 1]]


In [38]:
#Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])
#Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
b = np.repeat(a,3)
c = np.tile(a,3)
print(np.concatenate((b,c)))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [39]:
#Отримайте спільні елементи між a і b
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
com_el = np.intersect1d(a, b)
print(com_el)

[2 4]


In [40]:
#6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100)
a = np.random.uniform(1,50, 20)
a_sort= np.sort(a)
a_sort_desc= np.sort(a)[::-1]
for i in range(5):
    print(np.where(a==a_sort_desc[i]))
print(a, a_sort_desc)

(array([15], dtype=int64),)
(array([10], dtype=int64),)
(array([3], dtype=int64),)
(array([7], dtype=int64),)
(array([18], dtype=int64),)
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361] [48.95256545 44.67477576 42.39403048 41.466785   40.99501269 40.77247431
 33.86670515 29.17957314 27.62684215 21.80136195 14.64009987 14.42961361
 11.76517714 11.25090398 10.08108276  9.42510962  7.69862289  6.95688692
  6.31046763  1.23122395]


In [41]:
#7. Вилучіть усі значення NaN із одновимірного масиву
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[~np.isnan(a)]
print(a)

[1. 2. 3. 5. 6. 7.]


In [42]:
#8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
distance = np.linalg.norm(a - b)

print(distance)

6.708203932499369


In [52]:
#10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

np.random.seed(100) 
a = np.random.randint(0, 5, 10)
print(a)

repeat=np.zeros(len(a), dtype=bool)

counts= {}
for i, value in enumerate(a):
    if value in counts:
        counts[value] +=1
        if counts[value]>1:
            repeat[i] = True
    else:
        counts[value]=1

print(repeat)
        

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
