In [1]:
import numpy as np
from random import randint, random


In [5]:
#Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a1 = np.arange(1, 11)
print(a1)


[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a2= np.zeros((3, 3), dtype=int)
print(a2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [82]:
#Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
a3 = np.random.randint(1,10, size=(5,5))
print(a3)

[[5 2 1 8 6]
 [5 7 7 9 3]
 [9 1 3 8 4]
 [7 2 5 6 7]
 [8 5 9 5 6]]


In [130]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a4 = np.random.randint(0, 2, size=(4, 4)).astype(np.float64)
print(a4)

[[1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]]


In [144]:
#Exercise5 творіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a1 = np.random.randint(1,11, size=(5,))
a2 = np.random.randint(1,11, size =(5,))
print(a1, a2)
print((a1+a2), (a1-a2), (a1*a2))

[ 4  6  8  4 10] [2 3 6 2 1]
[ 6  9 14  6 11] [2 3 2 2 9] [ 8 18 48  8 10]


In [152]:
#Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a1 = np.random.randint(1,20, size = (7,))
a2 = np.random.randint(1,20, size = (7,))
print(a1, a2, (a1*a2))

[18 14  4 19 14 14 15] [ 5 12  4  5 14 17  8] [ 90 168  16  95 196 238 120]


In [23]:
#Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a1 = np.random.randint(1,11, size=(2,2))
a2 = np.random.randint(1,11, size=(2,3))

c = np.dot(a1,a2)

print(a1, a2, c)

SyntaxError: unexpected character after line continuation character (388680760.py, line 7)

In [192]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a1 = np.random.randint(1,11, size = (3,3))
a_inv = np.linalg.inv(a1)
print(a1, a_inv)

[[3 5 9]
 [6 2 1]
 [3 8 1]] [[-0.0173913   0.1942029  -0.03768116]
 [-0.00869565 -0.06956522  0.14782609]
 [ 0.12173913 -0.02608696 -0.06956522]]


In [232]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a1 = np.random.random(size=(4,4)).astype(np.float64)
at = a1.T
print(a1, at)

[[0.04177764 0.27851893 0.22779657 0.33160746]
 [0.4230289  0.0335741  0.33710203 0.60819944]
 [0.2668653  0.78433533 0.28488892 0.54611055]
 [0.30259569 0.02363335 0.21244553 0.8583734 ]] [[0.04177764 0.4230289  0.2668653  0.30259569]
 [0.27851893 0.0335741  0.78433533 0.02363335]
 [0.22779657 0.33710203 0.28488892 0.21244553]
 [0.33160746 0.60819944 0.54611055 0.8583734 ]]


In [222]:
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
m = np.random.randint(1,10, size=(3,4))
v = np.random.randint(1,10, size = (4,))
print(m, v, m*v)

[[7 5 4 1]
 [2 4 7 5]
 [4 4 2 1]] [5 7 9 8] [[35 35 36  8]
 [10 28 63 40]
 [20 28 18  8]]


In [238]:
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a1 = np.random.random(size=(2,3)).astype(np.float64)
v= np.random.random(size=(3,)).astype(np.float64)
d = a1*v
print(a1, v, d)

[[0.82333623 0.93614283 0.46218866]
 [0.60716329 0.50354039 0.89157432]] [0.34468406 0.06318186 0.00275879] [[0.28379087 0.05914724 0.00127508]
 [0.20927951 0.03181462 0.00245966]]


In [242]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a1 = np.random.randint(1,11, size=(2,2))
a2 = np.random.randint(1,11, size=(2,2))
c=a1*a2
print(c)


[[36 50]
 [21 15]]


In [244]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a1 = np.random.randint(1,11, size=(2,2))
a2 = np.random.randint(1,11, size=(2,2))
c=a1*a2
print(c)


[[56  6]
 [80 90]]


In [302]:
#Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a1 = np.random.randint(1,100, size=(5,5))
s = np.sum(a1)
print(a1, s)


[[59 81 37 36 31]
 [83 55 98 31 74]
 [ 7 35 37 39 18]
 [27 55 23 34 57]
 [81 71 54 60 58]] 1241


In [304]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a1 = np.random.randint(1,11, size=(4,4))
a2 = np.random.randint(1,11, size=(4,4))
c=a1-a2
print(c)

[[-5  1  2  2]
 [-3 -1 -1  1]
 [-4  3 -5 -1]
 [-2 -2  4  6]]


In [ ]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
#що містить суму елементів кожного рядка матриці.

In [312]:
#Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a= np.random.randint(1,20, size=(3,4))
aa =a*a
print(a, aa)


[[ 2 10  1 19]
 [ 6 10  1 12]
 [ 1  3  5 11]] [[  4 100   1 361]
 [ 36 100   1 144]
 [  1   9  25 121]]


In [310]:
#Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a= np.random.randint(1,51, size=(4,))
asqrt =np.sqrt(a)
print(a, asqrt)

[35 44 18  4] [5.91607978 6.63324958 4.24264069 2.        ]
